version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wex
    expose:
      - "5432"

  api:
    build: ./api
    env_file: ./api.env
    ports:
        - "4000:4000"
    depends_on:
      - db
